server:
  port: 8020

spring:
  kafka:
    bootstrap-servers: kafka:9092

  #Local MongoDB config
  data:
    mongodb:
      #uri: mongodb://localhost:27017/lowes
      database: lowes
      port: 27017
      host: localhost
